### ISSUE TITLE
Relationships error 

### ISSUE THREAD

**Issue by YaphetKG** [RedisGraph/redisgraph-bulk-loader#47]
When using Enforce Schema with out namespaces, an exception is raised 

`ERROR - 'RelationType' object has no attribute 'start_namespace' `
 here is the full stack trace 

```Traceback (most recent call last):
    bulk_insert (args, standalone_mode=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/airflow/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/airflow/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/redisgraph_bulk_loader/bulk_insert.py", line 112, in bulk_insert
    process_entities(reltypes)
  File "/home/airflow/.local/lib/python3.8/site-packages/redisgraph_bulk_loader/bulk_insert.py", line 31, in process_entities
    entity.process_entities()
  File "/home/airflow/.local/lib/python3.8/site-packages/redisgraph_bulk_loader/relation_type.py", line 53, in process_entities
    if self.start_namespace:
AttributeError: 'RelationType' object has no attribute 'start_namespace'

**Comment by YaphetKG** [comment]
Resolved by #46 .
